server:
    port: 8003
    tomcat:
        uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
  
datasource:
  mysql:
    JdbcUrl: jdbc:mysql://127.0.0.1:3306/javablog?useUnicode=true&characterEncoding=utf8&useSSL=false
    DriverClassName: com.mysql.jdbc.Driver
    Username: root
    Password: 123456
    useSSL: false
 